baseURL: "https://hugocen.github.io/"
title: Hugo's Blog
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Hugo's Blog
  description: "A mumbo jumbo of my thoughts and ideas."
  keywords: [Blog, Portfolio, PaperMod]
  author: Me
  # author: ["Me", "You"] # multiple authors
  images: ["/assets/Hugo-bw.jpg"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/assets/favicon.ico"
    favicon16x16: "/assets/favicon-16x16.png"
    favicon32x32: "/assets/favicon-32x32.png"
    apple_touch_icon: "/assets/apple-touch-icon.png"
    safari_pinned_tab: "/assets/safari-pinned-tab.svg"

  label:
    text: "Home"
    icon: /assets/apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Hugo's blog
    subtitle: "Software Engineer, Machine Learning Engineer, and Daydreamer"
    imageUrl: "/assets/Hugo-bw.jpg"
    imageWidth: 120
    imageHeight: 120
    imageTitle: me
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    - name: twitter
      url: "https://twitter.com/voldemort0731"
    - name: email
      url: "mailto:hugo.chen731@gmail.com"
    - name: github
      url: "https://github.com/hugocen"
    - name: LinkedIn
      url: "https://www.linkedin.com/in/tzu-yang-chen-62979b131/"
    - name: kaggle
      url: "https://www.kaggle.com/harry0731"

  analytics:
    google:
      SiteVerificationTag: "xCWuxveduvdrG0GBOlKWojCwkiPmHClrmNohKlfj4fo"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/<path_to_repo>/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: posts
      name: posts
      url: /posts/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai